Repository BinibinibiB/WeDoItTogether, pull requests merged in 2023-08, with the labels that each got.

#36 Test: TestViewController충돌 Test
  WeDoItTogether/WeDoItTogether.xcodeproj/project.pbxproj
  WeDoItTogether/WeDoItTogether/Controller/Home/DetailContentViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Home/TestViewController.swift
Labels: ✅ Test, 🍧 Heekwon

#37 Test: pin.title 변경
  WeDoItTogether/WeDoItTogether/Controller/Home/DetailContentViewController.swift
Labels: ✅ Test

#40 Test: pin.title 변경
  WeDoItTogether/WeDoItTogether/Controller/Home/DetailContentViewController.swift
Labels: ✅ Test, 🍧 Heekwon

#41 Test: pin.title
  WeDoItTogether/WeDoItTogether/Controller/Chatting/ChatListViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Home/DetailContentViewController.swift
  WeDoItTogether/WeDoItTogether/View/Chatting/ChatListView.swift
  WeDoItTogether/WeDoItTogether/View/Chatting/ChattingView.swift
Labels: ✅ Test, 🍧 Heekwon

#56 Feat: 프로필 변경 (이미지 변경 등)
  WeDoItTogether/WeDoItTogether/Controller/Profile/PasswordEditViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Profile/ProfileEditViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Profile/ProfileViewController.swift
  WeDoItTogether/WeDoItTogether/StorageManager.swift
  WeDoItTogether/WeDoItTogether/View/Profile/ProfileEditView.swift
  WeDoItTogether/WeDoItTogether/View/Profile/ProfileView.swift
Labels: ✨ Feature, 🍎 Yubin

#58 Feat: 알림 셋팅 및 프로필 뷰 수정
  WeDoItTogether/WeDoItTogether.xcodeproj/project.pbxproj
  WeDoItTogether/WeDoItTogether/Controller/Profile/ProfileEditViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Profile/ProfileViewController.swift
  WeDoItTogether/WeDoItTogether/Extensions/UNUserNotificationCenter+Extensions.swift
  WeDoItTogether/WeDoItTogether/Model/HomeTestModel.swift
  WeDoItTogether/WeDoItTogether/Others/AppDelegate.swift
  WeDoItTogether/WeDoItTogether/Others/SceneDelegate.swift
  WeDoItTogether/WeDoItTogether/View/Profile/ProfileEditView.swift
Labels: 🐞 BugFix, ✨ Feature, 🍎 Yubin

#64 Feat: 사용자 약속 알림 기능
  WeDoItTogether/WeDoItTogether/Controller/Home/AddContentViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Profile/ProfileViewController.swift
  WeDoItTogether/WeDoItTogether/Others/AppDelegate.swift
Labels: 🐞 BugFix, ✨ Feature, 🍎 Yubin

#72 Fix: AddContentView 오류 코드 수정
  WeDoItTogether/WeDoItTogether/View/Home/AddContentView.swift
Labels: 🐞 BugFix, 🐸 Youngseok

#73 Design: AddContentView 진입 시 tapbar 숨김
  WeDoItTogether/WeDoItTogether/Controller/Home/HomeViewController.swift
Labels: 🐸 Youngseok

#74 Feat: 약속 추가 시 Pin 터치를 통한 약속장소 설정 & Database 연동
  WeDoItTogether/WeDoItTogether.xcodeproj/project.pbxproj
  WeDoItTogether/WeDoItTogether/Controller/Home/AddContentMapViewController.swift
  WeDoItTogether/WeDoItTogether/Controller/Home/AddContentViewController.swift
  WeDoItTogether/WeDoItTogether/View/Home/AddContentView.swift
  WeDoItTogether/WeDoItTogether/View/Home/CustomMarkerView.swift
Labels: ✨ Feature, 🐸 Youngseok
